version: '3.8'

services:
  db:
    image: library/postgres:11.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/campaign:/var/lib/postgresql/data
