/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package flyway.jooq.test.app

import flyway.jooq.test.utilities.StringUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    println(StringUtils.join(tokens))
}
